# serving/fastapi/routes/lectures.py
# Knowledge package management endpoints.
# Packages are generated by the LectureMind cloud pipeline and imported here.

import logging
import uuid
import zipfile
import shutil
import json
from pathlib import Path
from typing import List

from fastapi import APIRouter, HTTPException, UploadFile, File, Form

from config import local_settings
from local.storage.lecture_registry import PROJECT_ROOT
from local.storage.registry_provider import get_registry
from local.loaders.package_validator import validate_package

PACKAGES_DIR = PROJECT_ROOT / "data" / "packages"
PACKAGES_DIR.mkdir(parents=True, exist_ok=True)

from serving.fastapi.schemas import (
    LectureInfo, UploadResponse, StatusResponse,
    NotesRequest, NotesResponse,
    FlashcardsRequest, FlashcardsResponse,
    QuizRequest, QuizResponse,
    LearningPathRequest, LearningPathResponse,
    SettingsUpdate, SettingsResponse,
)

logger = logging.getLogger(__name__)

router = APIRouter()


def _lec_to_info(lec: dict) -> LectureInfo:
    """Serialise a registry dict to a LectureInfo response model."""
    return LectureInfo(
        lecture_id=lec["lecture_id"],
        title=lec.get("title", ""),
        display_name=lec.get("display_name") or lec.get("title") or lec["lecture_id"],
        status=lec.get("status", "UNKNOWN"),
        chunk_count=lec.get("chunk_count", 0),
        segment_count=lec.get("segment_count", 0),
        duration=lec.get("duration"),
        course_name=lec.get("course_name"),
        speaker=lec.get("speaker"),
        description=lec.get("description"),
        language=lec.get("language"),
        created_at=lec.get("created_at"),
        pipeline_version=lec.get("pipeline_version"),
        package_version=lec.get("package_version"),
    )


@router.get("/lectures", response_model=List[LectureInfo])
async def list_lectures():
    """List all imported knowledge packages."""
    lectures = get_registry().list_lectures()
    return [_lec_to_info(lec) for lec in lectures]


@router.get("/lecture/{lecture_id}", response_model=LectureInfo)
async def get_lecture(lecture_id: str):
    """Get details for a specific knowledge package."""
    lecture = get_registry().get_lecture(lecture_id)
    if not lecture:
        raise HTTPException(status_code=404, detail="Package not found.")
    return _lec_to_info(lecture)


@router.post("/upload", response_model=UploadResponse)
async def import_knowledge_package(
    file: UploadFile = File(...),
    display_name: str = Form(None),
    description: str = Form(None),
):
    """
    Import a LectureMind Knowledge Package (.zip) generated by the cloud pipeline.
    Raw lecture files (PDF, video, audio, etc.) are rejected.
    """
    from local.loaders.manifest_validator import validate_manifest, ManifestValidationError

    logger.info("[import] Receiving package: %s", file.filename)

    if not file.filename or not file.filename.endswith(".zip"):
        logger.error("[import] Rejected: not a .zip file")
        raise HTTPException(
            status_code=400,
            detail=(
                "Only LectureMind Knowledge Packages (.zip) generated by the cloud "
                "pipeline can be imported. PDF, video, audio, and raw lecture files "
                "are not supported."
            ),
        )

    lecture_id = f"lecture_{uuid.uuid4().hex[:8]}"
    zip_path = PACKAGES_DIR / f"{lecture_id}.zip"
    extract_dir = PACKAGES_DIR / lecture_id

    try:
        # ── Step 1: register placeholder so status is trackable immediately ──
        logger.info("[import] Registering package placeholder: %s", lecture_id)
        get_registry().add_lecture(
            lecture_id=lecture_id,
            title=display_name or file.filename,
            display_name=display_name or file.filename,
            description=description or "",
            chunk_count=0,
            segment_count=0,
            package_path=str(extract_dir),
            status="UPLOADING",
        )

        # ── Step 2: save ZIP to disk ──────────────────────────────────────────
        logger.info("[import] Saving ZIP to %s", zip_path)
        with open(zip_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        # ── Step 2.5: enforce upload size limit (matches reranker route) ─────
        max_bytes = local_settings.MAX_PACKAGE_UPLOAD_MB * 1024 * 1024
        if zip_path.stat().st_size > max_bytes:
            raise ValueError(
                f"Package exceeds maximum allowed size "
                f"({local_settings.MAX_PACKAGE_UPLOAD_MB} MB)."
            )

        # ── Step 3: extract ───────────────────────────────────────────────────
        logger.info("[import] Extracting package to %s", extract_dir)
        extract_dir.mkdir(parents=True, exist_ok=True)
        try:
            with zipfile.ZipFile(zip_path, "r") as zf:
                # ZipSlip guard: reject any member whose resolved path escapes
                # the extraction directory (mirrors _safe_extract in reranker.py).
                # is_relative_to (not startswith) so sibling paths like
                # "<root>_evil/file" cannot bypass the check.
                extract_root = extract_dir.resolve()
                for member in zf.namelist():
                    member_path = (extract_dir / member).resolve()
                    if not member_path.is_relative_to(extract_root):
                        raise ValueError("Invalid path in ZIP archive.")
                zf.extractall(extract_dir)
        except zipfile.BadZipFile:
            raise ValueError("The uploaded file is not a valid ZIP archive. The package may be corrupted.")

        # ── Step 4: structural validation (required files present) ────────────
        logger.info("[import] Validating ZIP contents")
        get_registry().update_status(lecture_id, "VALIDATING")
        validate_package(extract_dir)  # raises ValueError with missing file list

        # ── Step 5: manifest validation (schema + count cross-checks) ─────────
        logger.info("[import] Validating manifest")
        validate_manifest(extract_dir)  # raises ManifestValidationError

        # ── Step 6: read metadata.json ────────────────────────────────────────
        logger.info("[import] Reading metadata")
        metadata_path = extract_dir / "metadata.json"
        metadata = {}
        if metadata_path.exists():
            with open(metadata_path, "r", encoding="utf-8") as f:
                metadata = json.load(f)

        # ── Step 7: read manifest.json ────────────────────────────────────────
        logger.info("[import] Reading manifest")
        manifest_path = extract_dir / "manifest.json"
        with open(manifest_path, "r", encoding="utf-8") as f:
            manifest_data = json.load(f)

        # ── Step 8: enrich registry with all available metadata ───────────────
        logger.info("[import] Enriching package metadata")
        title_from_meta = metadata.get("title") or metadata.get("course_name", f"Package {lecture_id}")
        get_registry().update_metadata(
            lecture_id,
            title=title_from_meta,
            # Use user-supplied display_name; fall back to metadata title
            display_name=display_name or title_from_meta,
            description=description or metadata.get("description", ""),
            chunk_count=manifest_data.get("chunk_count", 0),
            segment_count=manifest_data.get("segment_count", 0),
            # Rich optional metadata from cloud pipeline
            duration=metadata.get("duration", 0.0),
            course_name=metadata.get("course_name", ""),
            speaker=metadata.get("speaker", "") or metadata.get("instructor", ""),
            language=metadata.get("language", ""),
            pipeline_version=manifest_data.get("pipeline_version", ""),
            package_version=manifest_data.get("package_version", ""),
        )

        # ── Step 9: load vectors into Qdrant ──────────────────────────────────
        logger.info("[import] Loading vector index (Qdrant)")
        get_registry().update_status(lecture_id, "INDEXING")
        from local.loaders.qdrant_loader import load_qdrant
        load_qdrant(extract_dir, lecture_id=lecture_id)

        # ── Step 10: load graph into Neo4j ────────────────────────────────────
        logger.info("[import] Loading knowledge graph (Neo4j)")
        from local.loaders.neo4j_loader import load_neo4j
        load_neo4j(extract_dir, lecture_id)

        get_registry().update_status(lecture_id, "READY")

        # ── Step 11: initialise query workflow ────────────────────────────────
        logger.info("[import] Initializing query workflow")
        from serving.fastapi.routes import query as query_routes
        query_routes.activate_lecture(lecture_id)

        logger.info("[import] Import complete: %s", lecture_id)
        return UploadResponse(
            lecture_id=lecture_id,
            status="READY",
            message="Knowledge package imported successfully.",
        )

    except ManifestValidationError as mve:
        logger.error("[import] Failed at Validating manifest: %s", mve)
        get_registry().update_status(lecture_id, "FAILED")
        raise HTTPException(status_code=400, detail=f"Manifest validation failed: {mve}")

    except ValueError as ve:
        logger.error("[import] Failed at Validating ZIP: %s", ve)
        get_registry().update_status(lecture_id, "FAILED")
        raise HTTPException(status_code=400, detail=str(ve))

    except Exception as e:
        logger.error("[import] Failed at package import: %s", e, exc_info=True)
        if lecture_id in get_registry()._registry["lectures"]:
            get_registry().update_status(lecture_id, "FAILED")
        raise HTTPException(
            status_code=500,
            detail=f"Import failed: {e}",
        )


@router.get("/status/{lecture_id}", response_model=StatusResponse)
async def get_status(lecture_id: str):
    """Get import status for a knowledge package."""
    lecture = get_registry().get_lecture(lecture_id)
    if not lecture:
        return StatusResponse(lecture_id=lecture_id, status="UNKNOWN", progress=0.0)
    status = lecture.get("status", "UNKNOWN")
    return StatusResponse(
        lecture_id=lecture_id,
        status=status,
        progress=100.0 if status == "READY" else 0.0,
    )


@router.patch("/lectures/{lecture_id}/rename", response_model=LectureInfo)
async def rename_lecture(lecture_id: str, body: dict):
    """Rename a knowledge package display name."""
    lecture = get_registry().get_lecture(lecture_id)
    if not lecture:
        raise HTTPException(status_code=404, detail="Package not found.")
    new_name = (body.get("display_name") or "").strip()
    if len(new_name) < 3 or len(new_name) > 80:
        raise HTTPException(
            status_code=400,
            detail="Package name must be between 3 and 80 characters.",
        )
    get_registry().update_metadata(lecture_id, display_name=new_name)
    return _lec_to_info(get_registry().get_lecture(lecture_id))


@router.delete("/lectures/{lecture_id}", status_code=204)
async def delete_lecture(lecture_id: str):
    """Delete a single lecture completely."""
    lecture = get_registry().get_lecture(lecture_id)
    if not lecture:
        raise HTTPException(status_code=404, detail="Lecture not found")
        
    # Delete from Qdrant
    try:
        from qdrant_client import QdrantClient
        from config import local_settings
        from qdrant_client.http import models
        client = QdrantClient(url=local_settings.QDRANT_URL)
        client.delete(
            collection_name="lecturemind_chunks",
            points_selector=models.Filter(
                must=[models.FieldCondition(key="lecture_id", match=models.MatchValue(value=lecture_id))]
            ),
        )
    except Exception as e:
        logger.warning(f"Failed to delete Qdrant points for {lecture_id}: {e}")
        
    # Delete from Neo4j
    try:
        from neo4j import GraphDatabase
        driver = GraphDatabase.driver(local_settings.NEO4J_URI)
        with driver.session() as session:
            # Nodes store the runtime lecture_id as a property (see
            # neo4j_loader.py) — match on it so deletion actually removes
            # the lecture's nodes. The previous `n.id` predicate matched
            # nothing (no such property) and silently leaked graph data.
            session.run("MATCH (n) WHERE n.lecture_id = $lecture_id DETACH DELETE n", lecture_id=lecture_id)
    except Exception as e:
        logger.warning(f"Failed to delete Neo4j nodes for {lecture_id}: {e}")
        
    # Remove files
    package_path = Path(lecture.get("package_path", ""))
    if package_path.exists() and package_path.is_dir():
        import shutil
        shutil.rmtree(package_path)
    zip_path = Path(f"{package_path}.zip")
    if zip_path.exists():
        zip_path.unlink()
        
    # Remove from registry
    get_registry().remove_lecture(lecture_id)
    
    # Clear active workflow if this was it
    if get_registry().get_active_lecture_id() == lecture_id:
        from serving.fastapi.routes import query as query_routes
        query_routes.clear_workflow()
        get_registry()._registry["last_active_lecture_id"] = None
        get_registry()._save()
        
    return None


@router.delete("/lectures", status_code=204)
async def reset_all_lectures():
    """Development Reset: Delete all imported lectures and clean DBs."""
    lectures = get_registry().list_lectures()
    for lec in lectures:
        package_path = Path(lec.get("package_path", ""))
        if package_path.exists() and package_path.is_dir():
            import shutil
            shutil.rmtree(package_path)
        zip_path = Path(f"{package_path}.zip")
        if zip_path.exists():
            zip_path.unlink()
            
    # Reset Qdrant
    try:
        from qdrant_client import QdrantClient
        from config import local_settings
        client = QdrantClient(url=local_settings.QDRANT_URL)
        client.delete_collection(collection_name="lecturemind_chunks")
    except Exception as e:
        logger.warning(f"Failed to reset Qdrant: {e}")
        
    # Reset Neo4j
    try:
        from neo4j import GraphDatabase
        from config import local_settings
        driver = GraphDatabase.driver(local_settings.NEO4J_URI)
        with driver.session() as session:
            session.run("MATCH (n) DETACH DELETE n")
    except Exception as e:
        logger.warning(f"Failed to reset Neo4j: {e}")
        
    get_registry()._registry = {"lectures": {}, "last_active_lecture_id": None}
    get_registry()._save()
    
    from serving.fastapi.routes import query as query_routes
    query_routes.clear_workflow()
    
    return None


@router.post("/notes", response_model=NotesResponse)
async def generate_notes(request: NotesRequest):
    """Generate structured Markdown notes for a lecture."""
    from serving.fastapi.routes import query as query_routes
    from serving.fastapi.learning_service import generate_notes as _gen_notes

    try:
        query_routes.activate_lecture(request.lecture_id)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    workflow = query_routes.get_workflow()
    if workflow is None:
        raise HTTPException(
            status_code=503,
            detail="Query engine not initialized. Load a knowledge package first.",
        )
    try:
        notes = _gen_notes(workflow=workflow, lecture_id=request.lecture_id)
    except Exception as exc:
        logger.error("Notes generation failed: %s", exc)
        notes = "Notes generation failed. Please try again."
    return NotesResponse(lecture_id=request.lecture_id, notes=notes)


@router.post("/flashcards", response_model=FlashcardsResponse)
async def generate_flashcards(request: FlashcardsRequest):
    """Generate flashcards for a lecture."""
    from serving.fastapi.routes import query as query_routes
    from serving.fastapi.learning_service import generate_flashcards as _gen_fc

    try:
        query_routes.activate_lecture(request.lecture_id)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    workflow = query_routes.get_workflow()
    if workflow is None:
        raise HTTPException(
            status_code=503,
            detail="Query engine not initialized. Load a knowledge package first.",
        )
    try:
        cards = _gen_fc(workflow=workflow, lecture_id=request.lecture_id, count=request.count)
    except Exception as exc:
        logger.error("Flashcards generation failed: %s", exc)
        cards = []
    return FlashcardsResponse(lecture_id=request.lecture_id, flashcards=cards)


@router.post("/quiz", response_model=QuizResponse)
async def generate_quiz(request: QuizRequest):
    """Generate quiz questions for a lecture."""
    from serving.fastapi.routes import query as query_routes
    from serving.fastapi.learning_service import generate_quiz as _gen_quiz

    try:
        query_routes.activate_lecture(request.lecture_id)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    workflow = query_routes.get_workflow()
    if workflow is None:
        raise HTTPException(
            status_code=503,
            detail="Query engine not initialized. Load a knowledge package first.",
        )
    try:
        questions = _gen_quiz(workflow=workflow, lecture_id=request.lecture_id, count=request.count)
    except Exception as exc:
        logger.error("Quiz generation failed: %s", exc)
        questions = []
    return QuizResponse(lecture_id=request.lecture_id, questions=questions)


@router.post("/learning_path", response_model=LearningPathResponse)
async def generate_learning_path(request: LearningPathRequest):
    """Generate a learning path for a lecture."""
    from serving.fastapi.routes import query as query_routes
    from serving.fastapi.learning_service import generate_learning_path as _gen_lp

    try:
        query_routes.activate_lecture(request.lecture_id)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    workflow = query_routes.get_workflow()
    if workflow is None:
        raise HTTPException(
            status_code=503,
            detail="Query engine not initialized. Load a knowledge package first.",
        )
    try:
        path = _gen_lp(workflow=workflow, lecture_id=request.lecture_id)
    except Exception as exc:
        logger.error("Learning path generation failed: %s", exc)
        path = []
    return LearningPathResponse(lecture_id=request.lecture_id, path=path)


@router.put("/settings", response_model=SettingsResponse)
async def update_settings(request: SettingsUpdate):
    """
    Update application settings.

    Legacy endpoint — kept for backward compatibility.
    Delegates to the new provider registry for actual persistence.
    Prefer PATCH /settings for new code.
    """
    from local.llm.provider_registry import get_provider_registry
    reg = get_provider_registry()
    updated = {}
    if request.ollama_model:
        reg.set_local_model(request.ollama_model)
        updated["ollama_model"] = request.ollama_model
    if request.top_k is not None:
        updated["top_k"] = request.top_k

    return SettingsResponse(status="updated", settings=updated)
