// Import Knowledge Package — Screen 2
//
// ARCHITECTURE NOTE:
// LectureMind NEVER processes raw lecture files locally.
// This page only accepts LectureMind Knowledge Packages (.zip)
// generated by the cloud pipeline.
//
// BUG FIX (stale closure):
// handleUpload previously used useCallback([file]) which closed over the
// initial empty values of displayName/description. The fix is to remove
// useCallback entirely so the function always reads current state on render.
"use client";
import { useState, useRef } from "react";
import { uploadLecture } from "@/services/api";
import Link from "next/link";
import {
  Package,
  UploadCloud,
  CheckCircle,
  X,
  AlertCircle,
  ShieldCheck,
  CheckSquare,
  Rocket,
  Lightbulb,
  FileArchive
} from "lucide-react";

// Validation constants — identical to backend.
const PACKAGE_NAME_MIN = 3;
const PACKAGE_NAME_MAX = 80;

function validatePackageName(name: string): string | null {
  const trimmed = name.trim();
  if (trimmed.length === 0) return "Package name is required.";
  if (trimmed.length < PACKAGE_NAME_MIN)
    return `Package name must be at least ${PACKAGE_NAME_MIN} characters.`;
  if (trimmed.length > PACKAGE_NAME_MAX)
    return `Package name must be at most ${PACKAGE_NAME_MAX} characters.`;
  return null;
}

interface InlineErrorProps {
  message: string;
}
function InlineError({ message }: InlineErrorProps) {
  return (
    <div className="flex items-start gap-3 bg-red-900/20 border border-red-500/30 p-4 rounded-xl">
      <AlertCircle size={18} className="text-red-400 mt-0.5 shrink-0" />
      <p className="text-red-200 text-sm font-medium">{message}</p>
    </div>
  );
}

export default function ImportPackagePage() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  
  const handleBrowse = () => {
    fileInputRef.current?.click();
  };

  const [file, setFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [result, setResult] = useState<{ lecture_id: string; status: string; message: string } | null>(null);
  const [pageError, setPageError] = useState<string | null>(null);
  const [dragActive, setDragActive] = useState(false);

  // Modal state — NOT inside useCallback to avoid stale closure.
  const [showModal, setShowModal] = useState(false);
  const [displayName, setDisplayName] = useState("");
  const [description, setDescription] = useState("");
  const [nameError, setNameError] = useState<string | null>(null);
  const [modalError, setModalError] = useState<string | null>(null);

  // ── Drag handlers ──────────────────────────────────────────────────────────
  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") setDragActive(true);
    else if (e.type === "dragleave") setDragActive(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files?.[0]) handleFileSelection(e.dataTransfer.files[0]);
  };

  // ── File selection ─────────────────────────────────────────────────────────
  const handleFileSelection = (selected: File | null) => {
    if (!selected) return;

    // Only LectureMind Knowledge Packages (.zip) are accepted.
    if (!selected.name.endsWith(".zip")) {
      setPageError(
        "Only LectureMind Knowledge Packages (.zip) generated by the cloud pipeline can be imported."
      );
      return;
    }

    setFile(selected);
    setPageError(null);
    setDisplayName("");
    setDescription("");
    setNameError(null);
    setModalError(null);
    setShowModal(true);
  };

  // ── Live name validation ───────────────────────────────────────────────────
  const handleNameChange = (value: string) => {
    setDisplayName(value);
    // Only show inline error after the user has started typing.
    if (value.length > 0) {
      setNameError(validatePackageName(value));
    } else {
      setNameError(null);
    }
  };

  // ── Submit — reads displayName/description from current render scope.
  // NOTE: NO useCallback here. This is intentional.
  // useCallback([file]) previously caused a stale closure where displayName
  // was always the empty string from the initial render, making every valid
  // name appear to fail the length check.
  const handleImport = async () => {
    const trimmedName = displayName.trim();
    const validationError = validatePackageName(displayName);
    if (validationError) {
      setNameError(validationError);
      return;
    }
    if (!file) return;

    console.debug("[ImportPage] packageName=", JSON.stringify(trimmedName), "length=", trimmedName.length);

    setUploading(true);
    setModalError(null);
    setShowModal(false);

    try {
      const res = await uploadLecture(file, trimmedName, description.trim());
      setResult(res);
    } catch (e: unknown) {
      const rawMsg = e instanceof Error ? e.message : "Import failed.";

      // Parse backend detail message from the error string.
      // The api.ts layer throws: "Upload failed 4xx: <json_body>"
      let detail = rawMsg;
      const jsonStart = rawMsg.indexOf("{");
      if (jsonStart !== -1) {
        try {
          const parsed = JSON.parse(rawMsg.slice(jsonStart));
          if (parsed?.detail) detail = parsed.detail;
        } catch {
          // Keep rawMsg as detail.
        }
      }

      // Strip HTTP prefix for display.
      detail = detail.replace(/^Upload failed \d+:\s*/i, "").trim();

      setPageError(detail || "Import failed. Please try again.");
    } finally {
      setUploading(false);
    }
  };

  // ── Derived: is the Create Package button enabled? ─────────────────────────
  const isNameValid = validatePackageName(displayName) === null;

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <div className="upload-shell">
      {/* Hero Section */}
      <div className="upload-hero">
        <h1 className="upload-title">Import <span>Knowledge Package</span></h1>
        <p className="upload-subtitle">
          Bring your processed lectures offline. Upload a LectureMind package to instantly explore, query, and learn.
        </p>
      </div>

      {/* Format Info Card */}
      <div className="upload-info-card">
        <div className="upload-info-icon">
          <CheckCircle size={28} />
        </div>
        <div className="upload-info-content">
          <h3>LectureMind Knowledge Package (.zip)</h3>
          <p>Generated exclusively by the LectureMind Cloud Pipeline.</p>
          <div className="upload-info-rejected">
            <span><X size={14} /> PDF</span>
            <span><X size={14} /> Video</span>
            <span><X size={14} /> Audio</span>
            <span><X size={14} /> Raw Files</span>
          </div>
        </div>
        <div className="text-gray-600 opacity-30 hidden md:block">
          <FileArchive size={80} />
        </div>
      </div>

      {/* Main Drag & Drop Area */}
      <div
        className={`upload-drop-card ${dragActive ? "drag-active" : ""} ${uploading ? "disabled" : ""}`}
        onDragEnter={handleDrag}
        onDragLeave={handleDrag}
        onDragOver={handleDrag}
        onDrop={handleDrop}
      >
        <div className="upload-drop-glow" />
        
        <input
          ref={fileInputRef}
          type="file"
          accept=".zip,application/zip"
          onChange={(e) => handleFileSelection(e.target.files?.[0] ?? null)}
          className="hidden"
          style={{ display: "none" }}
          disabled={uploading}
        />
        
        {file ? (
          <div className="flex flex-col items-center z-10">
            <FileArchive size={64} className="text-green-500 mb-4 opacity-90" />
            <div className="flex items-center gap-2 mb-2 text-green-400 font-medium text-lg">
              <CheckCircle size={20} />
              Package Selected
            </div>
            <h3 className="text-2xl font-bold text-white mb-2">{file.name}</h3>
            <p className="text-gray-400 mb-8">
              {(file.size / (1024 * 1024)).toFixed(2)} MB • Ready to Import
            </p>
            <button 
              onClick={handleBrowse} 
              className="px-6 py-2 bg-gray-800 hover:bg-gray-700 text-white rounded-lg transition-colors border border-white/10"
            >
              Change File
            </button>
          </div>
        ) : (
          <div className="flex flex-col items-center z-10">
            <div className="upload-icon-wrapper">
              <UploadCloud size={80} />
            </div>
            
            <h3 className="text-xl font-medium mb-2">Drag & Drop your package here</h3>
            <p className="text-gray-400 mb-6">or click to browse</p>
            
            <button 
              onClick={handleBrowse}
              className="upload-custom-btn pointer-events-auto"
            >
              Choose ZIP File
            </button>
            
            <div className="upload-meta mt-6">
              <span>Max size: 500MB</span>
              <span>•</span>
              <span>Format: .zip</span>
            </div>
          </div>
        )}
      </div>

      {/* Page-level error (outside modal) */}
      {pageError && !showModal && (
        <div className="w-full max-w-[800px]">
          <InlineError message={pageError} />
        </div>
      )}

      {/* Success result */}
      {result && (
        <div className="w-full max-w-[800px] bg-green-900/20 border border-green-500/30 p-6 rounded-xl flex items-start gap-4">
          <CheckCircle className="text-green-500 mt-1 shrink-0" size={24} />
          <div>
            <h3 className="text-lg font-medium text-green-400 mb-1">
              Knowledge package imported successfully
            </h3>
            <div className="text-sm text-gray-400 font-mono mb-4">
              ID: {result.lecture_id}
            </div>
            <Link
              href={`/lecture/${result.lecture_id}`}
              className="inline-flex items-center gap-2 bg-green-500/20 text-green-400 px-4 py-2 rounded-lg hover:bg-green-500/30 transition-colors font-medium"
            >
              Open Package →
            </Link>
          </div>
        </div>
      )}

      {/* Feature Cards */}
      <div className="upload-feature-grid">
        <div className="upload-feature-card">
          <ShieldCheck size={28} className="upload-feature-icon" />
          <h4>Secure Import</h4>
          <p>Packages are safely verified and indexed before import.</p>
        </div>
        <div className="upload-feature-card">
          <CheckSquare size={28} className="upload-feature-icon" />
          <h4>Integrity Verified</h4>
          <p>Package structure and required metadata are validated automatically.</p>
        </div>
        <div className="upload-feature-card">
          <Rocket size={28} className="upload-feature-icon" />
          <h4>Ready to Learn</h4>
          <p>Imported lectures become available immediately with full features.</p>
        </div>
      </div>

      {/* Helpful Tip Banner */}
      <div className="upload-tip-banner">
        <Lightbulb size={20} />
        <span>Tip: For best results, import packages generated exclusively by the LectureMind Cloud Pipeline.</span>
      </div>

      {/* ── Name Package Modal ──────────────────────────────────────────────── */}
      {showModal && (
        <div className="settings-modal-overlay">
          <div className="settings-modal">
            <div className="settings-modal-header">
              <h2 className="settings-modal-title flex items-center gap-2">
                <Package className="text-primary" /> Name Package
              </h2>
              <button
                onClick={() => {
                  setShowModal(false);
                  setFile(null);
                }}
                className="settings-modal-close"
              >
                <X size={20} />
              </button>
            </div>
            
            <p className="settings-modal-desc mt-0 mb-6 text-gray-400">
              Give this knowledge package a memorable name. You can rename it later.
            </p>

            <div className="settings-form">
              {/* Package Name */}
              <div className="settings-form-group">
                <label className="settings-label">
                  Package Name <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  value={displayName}
                  onChange={(e) => handleNameChange(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && isNameValid && handleImport()}
                  placeholder="e.g. Operating Systems"
                  className={`settings-input ${nameError ? "border-red-500 focus:border-red-400" : ""}`}
                  autoFocus
                  maxLength={PACKAGE_NAME_MAX}
                />
                <div className="flex justify-between mt-1 px-1">
                  {nameError ? (
                    <p className="text-red-400 text-xs">{nameError}</p>
                  ) : (
                    <span />
                  )}
                  <p className="text-gray-500 text-xs">{displayName.trim().length}/{PACKAGE_NAME_MAX}</p>
                </div>
              </div>

              {/* Description */}
              <div className="settings-form-group">
                <label className="settings-label">
                  Description <span className="settings-label-optional">(optional)</span>
                </label>
                <input
                  type="text"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="e.g. Week 4 — Deadlocks and Scheduling"
                  className="settings-input"
                />
              </div>
            </div>

            {/* Modal-level error (from failed submission attempt) */}
            {modalError && (
               <div className="settings-validation error mt-4">
                 <AlertCircle size={16} /> {modalError}
               </div>
            )}

            <div className="settings-modal-actions mt-8">
              <button
                onClick={() => {
                  setShowModal(false);
                  setFile(null);
                }}
                className="btn-secondary"
              >
                Cancel
              </button>
              <button
                onClick={handleImport}
                disabled={!isNameValid}
                className="btn-primary"
              >
                Create Package
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Uploading overlay ───────────────────────────────────────────────── */}
      {uploading && (
        <div className="settings-modal-overlay">
          <div className="bg-gray-900 p-8 rounded-2xl flex flex-col items-center border border-white/10 gap-4 shadow-2xl">
            <span className="animate-spin text-primary">
              <UploadCloud size={48} />
            </span>
            <h3 className="text-xl font-medium">Importing Knowledge Package...</h3>
            <p className="text-gray-400 text-sm">Extracting, validating, and indexing. Please wait.</p>
          </div>
        </div>
      )}
    </div>
  );
}
